import assert from "node:assert/strict";
import { createHash } from "node:crypto";
import { test } from "node:test";

import { OAuthAttemptService } from "./oauth-attempt.service";

// Fase 3 do gate de autenticação guest: `state` é gerado exclusivamente
// pelo backend, correlacionado por tentativa de OAuth (não por cookie
// global) — ver specs/no-guest-analysis-preview-auth-gate-diagnostic-plan-ADENDO-hardening.md
// seção 4.1. Nenhum destes testes toca banco real: mocka DatabaseService no
// mesmo padrão já usado em cv-adaptation.service.spec.ts.

const OAuthAttemptServiceCtor = OAuthAttemptService as unknown as new (
  ...args: unknown[]
) => OAuthAttemptService;

const hashOf = (raw: string) => createHash("sha256").update(raw).digest("hex");

test("create() succeeds for a valid guest job + possession token and returns an opaque state generated by the backend", async () => {
  const rawToken = "a".repeat(64);
  const hash = hashOf(rawToken);
  let createdData: Record<string, unknown> | null = null;

  const service = new OAuthAttemptServiceCtor({
    analysisJob: {
      findUnique: async () => ({
        ownerKind: "guest",
        guestPossessionTokenHash: hash,
        convertedAt: null,
      }),
    },
    oAuthAttempt: {
      create: async ({ data }: { data: Record<string, unknown> }) => {
        createdData = data;
        return { id: "attempt-1", ...data };
      },
    },
  });

  const result = await service.create({
    jobId: "job-1",
    guestPossessionToken: rawToken,
    conversionContext: "analysis_guest",
    journeySessionInternalId: "11111111-1111-1111-1111-111111111111",
    visitorId: "22222222-2222-2222-2222-222222222222",
  });

  // O cliente nunca escolhe/influencia state — só recebe o que o backend
  // gerou. randomBytes(32).toString("hex") => 64 caracteres hex.
  assert.match(result.state, /^[0-9a-f]{64}$/);
  assert.notEqual(result.state, rawToken);

  assert.equal(
    (createdData as Record<string, unknown> | null)?.analysisJobId,
    "job-1",
  );
  assert.equal(
    (createdData as Record<string, unknown> | null)?.conversionContext,
    "analysis_guest",
  );
  assert.equal(
    (createdData as Record<string, unknown> | null)?.journeySessionInternalId,
    "11111111-1111-1111-1111-111111111111",
  );
  assert.equal(
    (createdData as Record<string, unknown> | null)?.visitorId,
    "22222222-2222-2222-2222-222222222222",
  );
  assert.equal(
    typeof (createdData as Record<string, unknown> | null)?.expiresAt,
    "object",
  );
});

test("create() rejects an invalid possession token — jobId alone never grants creation of an OAuthAttempt", async () => {
  const hash = hashOf("correct-token");

  const service = new OAuthAttemptServiceCtor({
    analysisJob: {
      findUnique: async () => ({
        ownerKind: "guest",
        guestPossessionTokenHash: hash,
        convertedAt: null,
      }),
    },
    oAuthAttempt: { create: async () => ({}) },
  });

  await assert.rejects(
    () =>
      service.create({ jobId: "job-1", guestPossessionToken: "wrong-token" }),
    /invalid guest analysis reference/,
  );
});

test("create() rejects a job that does not exist, is not guest, or was already converted", async () => {
  const cases: Array<Record<string, unknown> | null> = [
    null,
    { ownerKind: "authenticated", guestPossessionTokenHash: null },
    {
      ownerKind: "guest",
      guestPossessionTokenHash: hashOf("token"),
      convertedAt: new Date(),
    },
  ];

  for (const jobRow of cases) {
    const service = new OAuthAttemptServiceCtor({
      analysisJob: { findUnique: async () => jobRow },
      oAuthAttempt: { create: async () => ({}) },
    });

    await assert.rejects(
      () => service.create({ jobId: "job-1", guestPossessionToken: "token" }),
      /invalid guest analysis reference/,
    );
  }
});

test("resolveAndConsume() succeeds for a valid, unconsumed, unexpired state", async () => {
  const service = new OAuthAttemptServiceCtor({
    oAuthAttempt: {
      updateMany: async () => ({ count: 1 }),
      findUnique: async () => ({
        analysisJobId: "job-1",
        conversionContext: "analysis_guest",
        journeySessionInternalId: "sid-1",
        visitorId: "vid-1",
      }),
    },
  });

  const resolved = await service.resolveAndConsume("valid-state");

  assert.deepEqual(resolved, {
    analysisJobId: "job-1",
    conversionContext: "analysis_guest",
    journeySessionInternalId: "sid-1",
    visitorId: "vid-1",
  });
});

test("resolveAndConsume() returns null for a state that does not exist", async () => {
  const service = new OAuthAttemptServiceCtor({
    oAuthAttempt: {
      // updateMany não casa where.consumedAt:null + where.state inexistente
      // => count 0, exatamente como o Prisma real faria.
      updateMany: async () => ({ count: 0 }),
      findUnique: async () => null,
    },
  });

  const resolved = await service.resolveAndConsume("nonexistent-state");
  assert.equal(resolved, null);
});

test("resolveAndConsume() returns null for an expired state", async () => {
  const service = new OAuthAttemptServiceCtor({
    oAuthAttempt: {
      // A cláusula expiresAt > now() do updateMany real não casaria — o
      // mock replica o resultado (count 0) sem reimplementar SQL.
      updateMany: async () => ({ count: 0 }),
      findUnique: async () => ({
        analysisJobId: "job-1",
        conversionContext: null,
        journeySessionInternalId: null,
        visitorId: null,
      }),
    },
  });

  const resolved = await service.resolveAndConsume("expired-state");
  assert.equal(resolved, null);
});

test("resolveAndConsume() rejects a state that was already consumed — replay never succeeds", async () => {
  let calls = 0;
  const service = new OAuthAttemptServiceCtor({
    oAuthAttempt: {
      updateMany: async () => {
        calls += 1;
        // Primeira chamada consome (count 1); qualquer chamada seguinte
        // com o mesmo state já teria consumedAt setado no banco real =>
        // count 0. Simulamos isso diretamente pelo número da chamada.
        return { count: calls === 1 ? 1 : 0 };
      },
      findUnique: async () => ({
        analysisJobId: "job-1",
        conversionContext: null,
        journeySessionInternalId: null,
        visitorId: null,
      }),
    },
  });

  const first = await service.resolveAndConsume("state-x");
  const replay = await service.resolveAndConsume("state-x");

  assert.notEqual(first, null);
  assert.equal(replay, null);
});

test("callback duplicado: resolver o mesmo state duas vezes em sequência rápida (mesma janela) nunca resolve com sucesso duas vezes", async () => {
  let consumedAt: Date | null = null;

  const service = new OAuthAttemptServiceCtor({
    oAuthAttempt: {
      updateMany: async () => {
        if (consumedAt !== null) return { count: 0 };
        consumedAt = new Date();
        return { count: 1 };
      },
      findUnique: async () => ({
        analysisJobId: "job-duplicate-callback",
        conversionContext: null,
        journeySessionInternalId: null,
        visitorId: null,
      }),
    },
  });

  const results = await Promise.all([
    service.resolveAndConsume("dup-state"),
    service.resolveAndConsume("dup-state"),
  ]);

  const successes = results.filter((r) => r !== null);
  assert.equal(successes.length, 1);
});

test("duas abas com dois jobs diferentes: cada state resolve para o analysisJobId correto, sem cruzar", async () => {
  const attempts: Record<
    string,
    { analysisJobId: string; consumedAt: Date | null }
  > = {
    "state-tab-a": { analysisJobId: "job-a", consumedAt: null },
    "state-tab-b": { analysisJobId: "job-b", consumedAt: null },
  };

  const service = new OAuthAttemptServiceCtor({
    oAuthAttempt: {
      updateMany: async ({ where }: { where: { state: string } }) => {
        const attempt = attempts[where.state];
        if (!attempt || attempt.consumedAt !== null) return { count: 0 };
        attempt.consumedAt = new Date();
        return { count: 1 };
      },
      findUnique: async ({ where }: { where: { state: string } }) => {
        const attempt = attempts[where.state];
        if (!attempt) return null;
        return {
          analysisJobId: attempt.analysisJobId,
          conversionContext: null,
          journeySessionInternalId: null,
          visitorId: null,
        };
      },
    },
  });

  // Aba A completa o login primeiro.
  const resolvedForTabA = await service.resolveAndConsume("state-tab-a");
  assert.equal(resolvedForTabA?.analysisJobId, "job-a");

  // Aba B, independente, completa depois — precisa continuar resolvendo
  // pro job dela, nunca pro job da aba A.
  const resolvedForTabB = await service.resolveAndConsume("state-tab-b");
  assert.equal(resolvedForTabB?.analysisJobId, "job-b");

  // Nenhum dos dois pode ser reconsumido.
  assert.equal(await service.resolveAndConsume("state-tab-a"), null);
  assert.equal(await service.resolveAndConsume("state-tab-b"), null);
});
