-- Sprint 7: adiciona sinais de Growth/Marketing, Business Analytics e CX
-- Digital ao filtro semantico do Radar de Oportunidades, criando a v16 a
-- partir da v15 ativa (91 techSignals) + os novos termos da spec
-- (deduplicados). noiseSignals permanece inalterado -- SDR/BDR/business
-- analyst/customer success sao termos contexto-dependentes; o LLM de
-- enriquecimento classifica como OTHER quando o contexto nao se aplica
-- (ver regras em job-enrichment-llm.ts). Idempotente via ON CONFLICT no
-- "version" unico, mesmo padrao da migration de seed da v1 original.
INSERT INTO "SemanticFilterConfig" (
  "id",
  "version",
  "isActive",
  "techSignals",
  "noiseSignals",
  "description",
  "createdAt",
  "updatedAt"
)
VALUES (
  'seed-semantic-filter-config-v16',
  'v16',
  true,
  ARRAY[
    'desenvolvedor',
    'developer',
    'engenheiro',
    'engineer',
    'analista de dados',
    'data analyst',
    'data engineer',
    'data science',
    'software',
    'backend',
    'front-end',
    'frontend',
    'full stack',
    'fullstack',
    'mobile',
    'devops',
    'cloud',
    'sre',
    'platform',
    'site reliability',
    'produto',
    'product manager',
    'product owner',
    'ux',
    'ui designer',
    'qa',
    'quality assurance',
    'teste',
    'tester',
    'automação de testes',
    'segurança',
    'security',
    'cybersecurity',
    'cyber',
    'pentest',
    'infraestrutura',
    'infra',
    'redes',
    'network',
    'arquiteto',
    'architect',
    'solutions architect',
    'scrum master',
    'agile coach',
    'tech lead',
    'cto',
    'cio',
    'machine learning',
    'inteligência artificial',
    'ia',
    'llm',
    'mlops',
    'analytics',
    'business intelligence',
    'bi',
    'database',
    'dba',
    'banco de dados',
    'suporte de ti',
    'suporte técnico ti',
    'analista de ti',
    'sistemas',
    'analista de sistemas',
    'gerente de ti',
    'coordenador de ti',
    'head de tecnologia',
    'head de dados',
    'head de produto',
    'head de engenharia',
    'suporte tecnico',
    'gerente projetos',
    'data porduct owner',
    'analista service desk',
    'analista seguranca',
    'cientista de dados',
    'analista de suporte',
    'business analyst',
    'oracle epm',
    'data scientist',
    'appsec',
    'automação',
    'rpa',
    'devsecops',
    'middleware',
    'arquitetura de soluções',
    'sap',
    'telecom',
    'salesforce',
    'ai',
    'automation',
    'tecnologia',
    'growth hacker',
    'growth analyst',
    'performance marketing',
    'seo specialist',
    'sem specialist',
    'cro analyst',
    'crm analyst',
    'marketing ops',
    'marketing digital',
    'lifecycle marketing',
    'retention specialist',
    'sdr',
    'sales development representative',
    'bdr',
    'business development representative',
    'revenue operations',
    'demand generation',
    'inbound sales',
    'outbound sales',
    'business intelligence analyst',
    'revenue ops',
    'pricing analyst',
    'market intelligence',
    'strategic analyst',
    'planning analyst',
    'commercial analyst',
    'sales ops',
    'go-to-market',
    'customer experience designer',
    'cx analyst',
    'conversational designer',
    'ux researcher',
    'service designer'
  ]::text[],
  ARRAY[
    'enfermeiro',
    'técnico de enfermagem',
    'médico',
    'farmacêutico',
    'biomédico',
    'fisioterapeuta',
    'psicólogo',
    'nutricionista',
    'recepcionista',
    'atendente',
    'operador de caixa',
    'vendedor',
    'assistente de vendas',
    'agente de vendas',
    'montador',
    'mecânico',
    'eletricista',
    'soldador',
    'motorista',
    'operador de máquinas',
    'assistente de loja',
    'fiscal de loja',
    'gerente de loja',
    'estoquista',
    'armazenista',
    'almoxarife',
    'auxiliar de limpeza',
    'zelador',
    'porteiro',
    'aprendiz',
    'jovem aprendiz',
    'pedagogo',
    'professor',
    'docente',
    'advogado',
    'contador',
    'analista contábil',
    'analista fiscal'
  ]::text[],
  'Sprint 7: adiciona sinais de Growth/Marketing, Business Analytics e CX Digital',
  CURRENT_TIMESTAMP,
  CURRENT_TIMESTAMP
)
ON CONFLICT ("version") DO NOTHING;

-- Desativa a v15 caso ainda esteja ativa (o INSERT acima ja cria a v16
-- como ativa; sem isso as duas ficariam isActive=true simultaneamente).
UPDATE "SemanticFilterConfig"
SET "isActive" = false, "updatedAt" = CURRENT_TIMESTAMP
WHERE "version" != 'v16' AND "isActive" = true;
